name: "SSH Execute Commands"
description: "Execute commands on one ore more hosts with a private key as auth"
author: "JimCronqvist"
inputs:
  command:
    description: "Command(s) to execute on the remote server."
    required: true
  hosts:
    description: "Hostname or IP address of the remote server(s). Separate multiple servers with a blank space. Example: 'user@mydomain.com:22 user@otherdomain.com:2222'"
    required: true
  privateKey:
    description: "The private key (id_rsa) content for authenticating to the SSH server(s). Recommended to store it as a GitHub Secret."
    required: true
  debug:
    description: "Used to view all environment variables in the logs, please note that this could expose sensitive data."
    default: false
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  color: "gray-dark"
  icon: "terminal"